# Generated by Django 3.0.8 on 2020-07-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='link',
            field=models.URLField(default='https://twitter.com/', verbose_name='リンク'),
        ),
    ]
